# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'devops_app_amedee'
        repository: 'devops-app-amedee'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

      #!/bin/bash
# script to install ansible to deploy some ressource using playbook  
sudo apt-add-repository ppa:ansible/ansible
sudo apt -y update
sudo apt -y install ansible python-pip
sudo pip install azure[azure] azure packaging msrestazure azure-storage     
